apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-blobs
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: <your-class>
