apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  REGISTRY_POSTGRES: {{ include "registry.postgresUrl" . }}
  REGISTRY_ADMIN_USER: {{ .Values.admin.user | quote }}
  REGISTRY_ADMIN_PASS: {{ .Values.admin.password | quote }}
  REGISTRY_AUTH_SECRET: {{ .Values.authSecret | quote }}
  REGISTRY_VAULT_KEY: {{ .Values.vaultKey | quote }}
