{{- if and .Values.ingress.enabled (eq (.Values.ingress.mode | default "ingress") "istio-vs") }}
{{- $fullname := include "registry.fullname" . }}
{{- $hosts := .Values.ingress.hosts }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range $host := $hosts }}
    - {{ $host }}
    {{- end }}
  gateways:
    - {{ .Values.ingress.istio.gateway }}
  http:
    {{- if .Values.ingress.tls.enabled }}
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 308
    {{- end }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $fullname }}
            port:
              number: {{ $.Values.service.port }}
{{- end }}
